version: 2
jobs:
  build:
    working_directory: ~/motion
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle.kts" }}
      - run:
          name: Build and run tests
          command: ./gradlew -q build
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results/test/
  publish:
    working_directory: ~/motion
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - restore_cache:
          key: gradle-{{ checksum "build.gradle.kts" }}
      - run:
          name: Publish snapshot
          command: ./gradlew -q publish -Pversion="${CIRCLE_TAG}"
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /[0-9]+\..*/
            branches:
              ignore:
                - gh-pages
      - publish:
          context: jfrog
          requires:
            - build
          filters:
            branches:
              ignore: master
            tags:
              only: /[0-9]+\..*/
